// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ActionKind = "move" | "copy" | "reject" | "rename" | "keep";

export type AppInfo = { version: string, dbPath: string, audio: AudioInfo | null, audioError: string | null, };

export type AudioInfo = { sampleRate: number, channels: number, bufferFrames: number, cacheBytes: number, cacheLimitBytes: number, cacheEntries: number, latencyP50Ms: number, latencyP95Ms: number, shots: number, };

export type Destination = { id: number, projectId: number, name: string, relPath: string, hotkey: string | null, color: string, sortOrder: number, count: number, };

export type LibraryPage = { rows: Array<SampleRow>, total: number, offset: number, };

export type LibraryQuery = { sourceId: number | null, search: string | null, status: StatusFilter, sort: SortBy, 
/**
 * Filtro de duración en ms. Separa los one-shots de los loops, que es la primera
 * pregunta que se hace cualquiera al ordenar una librería.
 */
minDurationMs: number | null, maxDurationMs: number | null, 
/**
 * Valoración mínima (0 = sin filtrar).
 */
minRating: number, offset: number, limit: number, };

export type LibraryStats = { total: number, pending: number, kept: number, rejected: number, moved: number, analyzed: number, duplicates: number, };

export type PlaybackStarted = { sampleId: number, 
/**
 * Milisegundos desde el arranque del proceso: el front interpola el cabezal desde aquí
 * con requestAnimationFrame, sin un solo evento IPC por frame.
 */
startedAtMs: number, durationMs: number, startOffsetMs: number, looping: boolean, };

export type Project = { id: number, name: string, destRoot: string, mode: TriageMode, createdAt: number, };

export type SampleDetail = { row: SampleRow, absPath: string, loudnessDb: number | null, bitDepth: number | null, tags: Array<string>, };

/**
 * Lo que la lista virtualizada necesita para pintar una fila. Nada más: cada campo de más
 * se multiplica por 100.000 filas.
 */
export type SampleRow = { id: number, filename: string, relPath: string, ext: string, size: number, durationMs: number | null, sampleRate: number | null, channels: number | null, analyzed: boolean, status: SampleStatus, rating: number, duplicate: boolean, destination: string | null, };

export type SampleStatus = "pending" | "kept" | "rejected" | "moved";

/**
 * Progreso del escaneo. Se emite por `Channel` con throttle: nunca uno por archivo.
 */
export type ScanProgress = { found: number, indexed: number, analyzed: number, pendingAnalysis: number, done: boolean, };

export type SessionProgress = { done: number, total: number, };

export type SortBy = "path" | "filename" | "duration" | "size" | "loudness" | "recent";

export type SourceInfo = { id: number, path: string, addedAt: number, total: number, analyzed: number, };

export type StatusFilter = "all" | "pending" | "decided" | "kept" | "rejected" | "duplicates";

export type TrashSummary = { files: number, bytes: number, };

export type TriageMode = "move" | "copy";

/**
 * Resultado de una operación de triaje: lo que el frontend necesita para actualizar la UI
 * sin volver a pedir la página entera.
 */
export type TriageResult = { batchId: string, affected: Array<number>, destinationId: number | null, destinationCount: number | null, kind: ActionKind, };

export type UndoResult = { batchId: string, restored: Array<number>, focusSampleId: number | null, kind: ActionKind, destinationId: number | null, destinationCount: number | null, };
